import { unitById } from "@/lib/collections/syllabus";
import { prisma } from "@/lib/db";
import { generateCards, type CardType, type GeneratedCard, type LexemeForCards } from "@/lib/srs/cards";
import { emptyScheduling } from "@/lib/srs/scheduler";

/**
 * Building a deck out of course units, in a fixed number of queries.
 *
 * This is a rewrite of a loop, and the loop is worth describing because the
 * shape of it is the fault. Adding a unit used to read one lexeme, read that
 * learner's existing cards for it and insert, per word, and onboarding then ran
 * that per unit: six units of eighteen words was somewhere over three hundred
 * sequential round trips, plus a session validation per unit and three
 * `revalidatePath` calls per unit on top. Nothing about it was wrong and all of
 * it was slow, and the place it was slowest is the one place it had to be fast,
 * because "Building your deck..." is the last thing a stranger sees before they
 * decide whether this app works. On a hosted database that spinner ran for
 * tens of seconds and looked like a hang, which is what it was reported as.
 *
 * So the work is the same work and the queries are three: every lexeme the
 * chosen units name, every card this learner already holds for those lexemes,
 * and the insert. Cards are still generated by `generateCards` rather than
 * counted by a formula, because the deck a learner gets and the number the
 * screen promised them have to come from one place.
 */

/**
 * Rows per insert.
 *
 * `createMany` sends one statement, and Postgres takes at most 65535 bound
 * parameters in one of those. A card binds sixteen columns, so the ceiling is
 * around four thousand rows and a whole level of the course clears it: A1 alone
 * builds a little over two thousand cards, and somebody adding several levels
 * at once would hit the limit as a database error rather than as slowness.
 * Five hundred is well under it and still turns the largest deck this app can
 * build into a handful of inserts.
 */
const INSERT_CHUNK = 500;


export interface DeckPlan {
  /** Lemmas in the order the units introduce them, each with the cards it earns. */
  readonly lemmas: readonly string[];
  /** Card types per lemma, unioned where two units name the same word. */
  readonly types: ReadonlyMap<string, CardType[]>;
}

/**
 * What a set of units asks for, before the dictionary is consulted.
 *
 * A word can appear in more than one unit, and the units need not agree about
 * which cards it is for: `koer` is a recognition word in one unit and a
 * case-form word in another. Adding both units should give both, so the types
 * are unioned rather than last-one-wins. The order is the course's own, because
 * the first cards somebody sees should be the ones their first unit leads with.
 *
 * Pure: the syllabus is a constant, so this needs no database and no owner.
 */
export function planUnits(unitIds: readonly string[]): DeckPlan {
  const types = new Map<string, CardType[]>();
  const lemmas: string[] = [];

  for (const unitId of unitIds) {
    const unit = unitById(unitId);
    if (!unit) continue;
    for (const lemma of unit.lemmas) {
      const existing = types.get(lemma);
      if (existing) {
        for (const type of unit.cardTypes) if (!existing.includes(type)) existing.push(type);
      } else {
        types.set(lemma, [...unit.cardTypes]);
        lemmas.push(lemma);
      }
    }
  }

  return { lemmas, types };
}

/** A lexeme loaded for card building, with the id the card row needs. */
type DeckLexeme = LexemeForCards & { id: string };

/** Every card the plan would build, in course order, for lexemes the dictionary has. */
function buildCards(plan: DeckPlan, lexemes: readonly DeckLexeme[]): (GeneratedCard & { lexemeId: string })[] {
  const byLemma = new Map(lexemes.map((l) => [l.lemma, l]));
  const out: (GeneratedCard & { lexemeId: string })[] = [];

  for (const lemma of plan.lemmas) {
    const lexeme = byLemma.get(lemma);
    if (!lexeme) continue;
    for (const card of generateCards(lexeme, plan.types.get(lemma) ?? [])) {
      out.push({ ...card, lexemeId: lexeme.id });
    }
  }

  return out;
}

/** The key a card is unique by, which is the key `addCardsFor` has always skipped on. */
const cardKey = (lexemeId: string, cardType: string, front: string) => `${lexemeId}|${cardType}|${front}`;

/**
 * The lexemes a plan names, with everything `generateCards` reads off one.
 *
 * `forms` is the reason this is a `select` rather than a bare `findMany`: a
 * case-form card is built from the genitive stem and a gap-fill from the stored
 * forms, so a lexeme without them silently produces two cards where it should
 * produce ten.
 */
async function loadLexemes(lemmas: readonly string[]): Promise<DeckLexeme[]> {
  return prisma.lexeme.findMany({
    where: { lemma: { in: [...lemmas] } },
    select: {
      id: true,
      lemma: true,
      translation: true,
      pos: true,
      gradation: true,
      gradationNote: true,
      government: true,
      examples: true,
      forms: { select: { formType: true, value: true, morphCode: true } },
    },
  });
}

export interface DeckPreview {
  /** Words the dictionary can actually fill. A lemma it does not have is not offered. */
  readonly words: number;
  /** Cards those words build, counted by building them rather than by a rule of thumb. */
  readonly cards: number;
}

/**
 * How big a deck these units come to, without writing one.
 *
 * The screen that offers a starter deck has to be able to say how large it is,
 * and the only honest way to say so is to build the cards and count them. Two
 * cards a word was the estimate this replaced and it is wrong by a lot: a
 * recognition and a production card are two, but a unit that drills cases adds
 * one per drilled case and a unit with recorded sentences adds up to two more,
 * so the A1 units come out near nine cards a word and the course as a whole
 * near seven. A first-run screen promising four hundred cards where the deck is
 * two thousand has misdescribed the next two years of somebody's evenings.
 */
export async function previewUnits(unitIds: readonly string[]): Promise<DeckPreview> {
  const plan = planUnits(unitIds);
  if (plan.lemmas.length === 0) return { words: 0, cards: 0 };

  const lexemes = await loadLexemes(plan.lemmas);

  const cards = buildCards(plan, lexemes);
  const words = new Set(cards.map((c) => c.lexemeId)).size;
  return { words, cards: cards.length };
}

export interface DeckResult {
  /** Cards written. Zero when everything was already in the deck. */
  readonly added: number;
  /** Words the dictionary had, whether or not they were already in the deck. */
  readonly words: number;
}

/**
 * Adds every word of one or more units to a learner's deck.
 *
 * Already-present cards are skipped, so re-adding a unit after finishing half
 * of it costs nothing and loses no scheduling. That was true of the per-word
 * version and stays true here; what changed is only how many round trips it
 * takes to be true.
 *
 * The owner is a parameter, so this lives here rather than in `app/actions.ts`:
 * every export in a `"use server"` file is a public endpoint, and one taking an
 * owner id would let a learner write cards into somebody else's deck.
 */
export async function addUnitsToDeck(
  ownerId: string, unitIds: readonly string[], source = "DICTIONARY",
): Promise<DeckResult> {
  const plan = planUnits(unitIds);
  if (plan.lemmas.length === 0) return { added: 0, words: 0 };

  const lexemes = await loadLexemes(plan.lemmas);
  if (lexemes.length === 0) return { added: 0, words: 0 };

  const existing = await prisma.card.findMany({
    where: { ownerId, lexemeId: { in: lexemes.map((l) => l.id) } },
    select: { lexemeId: true, cardType: true, front: true },
  });

  const seen = new Set(existing.map((c) => cardKey(c.lexemeId ?? "", c.cardType, c.front)));
  const fresh: (GeneratedCard & { lexemeId: string })[] = [];

  /*
    Deduplicated against this run as well as against the deck. Two units can
    name the same word, and although the types are unioned above, generating
    per lemma still has to be proof against a card the same lemma produced
    twice: the insert has no unique constraint to fall back on.
  */
  for (const card of buildCards(plan, lexemes)) {
    const key = cardKey(card.lexemeId, card.cardType, card.front);
    if (seen.has(key)) continue;
    seen.add(key);
    fresh.push(card);
  }

  const words = lexemes.length;
  if (fresh.length === 0) return { added: 0, words };

  const scheduling = emptyScheduling(new Date());
  const rows = fresh.map((c) => ({
    ownerId,
    lexemeId: c.lexemeId,
    cardType: c.cardType,
    front: c.front,
    back: c.back,
    hint: c.hint,
    targetCase: c.targetCase,
    source,
    due: scheduling.due,
    stability: scheduling.stability,
    difficulty: scheduling.difficulty,
    state: scheduling.state,
    learningSteps: scheduling.learningSteps,
  }));

  let added = 0;
  for (let i = 0; i < rows.length; i += INSERT_CHUNK) {
    const result = await prisma.card.createMany({ data: rows.slice(i, i + INSERT_CHUNK) });
    added += result.count;
  }

  return { added, words };
}
