/* GENERATED by scripts/draft-lines.ts. Do not add a line by hand.

   Every row was drafted by a model inside its scene's closed word list, passed
   the four checks in lib/scenes/gate.ts on the day named, and was read in the
   pull request that added it. The one field a person edits is `reviewed`,
   which a native speaker sets to true after reading the row, and which the
   chip on screen reads. Regenerate with `npm run draft:lines`; the script
   keeps rows that are already here and only drafts what is missing.
   (lib/scenes/scripted.ts is what reads this; ADR-025 amendment 1.) */
import type { ScriptedLine } from "./scripted";

export const BANK: readonly ScriptedLine[] = [
  { scene: "poodi-piima", beat: "close", text: "Head aega!", model: "minimax/minimax-m3:free", draftedAt: "2026-09-04", reviewed: false },
  { scene: "poodi-piima", beat: "greet", text: "Tere hommikust!", model: "minimax/minimax-m3:free", draftedAt: "2026-09-04", reviewed: false },
  { scene: "poodi-piima", beat: "greet", text: "Tere!", model: "minimax/minimax-m3:free", draftedAt: "2026-09-04", reviewed: false },
  { scene: "poodi-piima", beat: "inside", text: "Kas sa oled praegu poe juures?", model: "minimax/minimax-m3:free", draftedAt: "2026-09-04", reviewed: false },
  { scene: "poodi-piima", beat: "inside", text: "Kus pood praegu olema?", model: "minimax/minimax-m3:free", draftedAt: "2026-09-04", reviewed: false },
  { scene: "poodi-piima", beat: "inside", text: "Kus sa praegu oled, kas pood on lähedal?", model: "minimax/minimax-m3:free", draftedAt: "2026-09-04", reviewed: false },
];
