import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

/**
 * ESLint, on the flat config the CLI actually uses.
 *
 * `next lint` is deprecated in Next 15 and gone in 16; worse, with no config on
 * disk it drops into an interactive setup prompt, so `npm run lint` hung in CI
 * and in any non-interactive shell. `eslint .` reads this file and exits with a
 * status, which is the only behaviour a lint script is useful for.
 *
 * FlatCompat is here because `eslint-config-next` is still published as a
 * legacy (eslintrc) config; this is the shape Next's own migration codemod
 * produces.
 */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by Prisma, and not ours to style.
      "prisma/generated/**",
    ],
  },

  ...compat.extends("next/core-web-vitals", "next/typescript"),

  {
    rules: {
      /*
       * Project rules, each one earning its place rather than inherited wholesale.
       */

      // CLAUDE.md: "No `any` without a comment justifying it." The rule cannot
      // read comments, so it warns rather than errors — it is a prompt to
      // justify, not a block.
      "@typescript-eslint/no-explicit-any": "warn",

      // Unused code is usually a leftover from a refactor. `_`-prefixed names
      // are the escape hatch for a deliberately ignored argument.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],

      // Estonian text is full of apostrophes and quotes; React's own rule about
      // escaping them catches real rendering bugs, so it stays on.
      "react/no-unescaped-entities": "error",
    },
  },

  {
    // The browser test scripts are Node programs, not app code: they use
    // top-level await, console output and Playwright's own globals.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { console: "readonly", process: "readonly", Buffer: "readonly", URL: "readonly" },
    },
  },

  {
    // The service worker runs in a worker scope, where `self`, `caches` and
    // `Response` are the globals and there is no DOM.
    files: ["public/sw.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        self: "readonly",
        caches: "readonly",
        fetch: "readonly",
        Response: "readonly",
        URL: "readonly",
      },
    },
  },
];

export default config;
