/**
 * Achievement definitions and the pure logic that decides which are earned.
 *
 * Framework-free, like lib/estonian/ and lib/srs/ — every badge condition is a
 * deterministic function of stats pulled from the database, never of anything
 * generated by the AI tutor (ADR-005 does not apply here, but the same instinct
 * does: a badge is either honestly earned from real review history or it isn't).
 */

import { dayClock, type DayClock, type DayKey } from "@/lib/time/day";

export interface Badge {
  key: string;
  /** The badge's name, in Estonian. */
  title: string;
  /**
   * What the Estonian name says, in English.
   *
   * Not decoration. Every badge here is named in Estonian and a learner who
   * has just earned one is looking at it for the first time, which is the one
   * moment a word is worth reading. `Paarid paigas` under a description about
   * a match round teaches nothing; `the pairs are in place` teaches two words
   * somebody will meet again. It is a translation into English, which is the
   * one language this project may write (ADR-005).
   */
  gloss: string;
  description: string;
  /** Name of a lucide-react icon component; mapped to the real component in the UI. */
  icon: string;
}

export const BADGES: Badge[] = [
  { key: "first_review", title: "Esimene samm", gloss: "first step", description: "Complete your first review.", icon: "Sparkles" },
  { key: "streak_3", title: "Kolm järjest", gloss: "three in a row", description: "Reach a 3-day streak.", icon: "Flame" },
  { key: "streak_7", title: "Terve nädal", gloss: "a whole week", description: "Reach a 7-day streak.", icon: "Flame" },
  { key: "streak_30", title: "Terve kuu", gloss: "a whole month", description: "Reach a 30-day streak.", icon: "Flame" },
  { key: "streak_100", title: "Sada päeva", gloss: "a hundred days", description: "Reach a 100-day streak.", icon: "Flame" },
  { key: "reviews_100", title: "Sada kordust", gloss: "a hundred repetitions", description: "Complete 100 reviews in total.", icon: "Repeat" },
  { key: "reviews_500", title: "Viissada kordust", gloss: "five hundred repetitions", description: "Complete 500 reviews in total.", icon: "Repeat" },
  { key: "reviews_1000", title: "Tuhat kordust", gloss: "a thousand repetitions", description: "Complete 1,000 reviews in total.", icon: "Repeat" },
  { key: "cards_known_25", title: "Veerandsada teada", gloss: "twenty-five known", description: "Get 25 cards into the Known state.", icon: "BookCheck" },
  { key: "cards_known_100", title: "Sada teada", gloss: "a hundred known", description: "Get 100 cards into the Known state.", icon: "BookCheck" },
  { key: "deck_50", title: "Viiskümmend sõna", gloss: "fifty words", description: "Add 50 words to your dictionary.", icon: "Library" },
  { key: "deck_200", title: "Kakssada sõna", gloss: "two hundred words", description: "Add 200 words to your dictionary.", icon: "Library" },
  { key: "case_master", title: "Käänded selged", gloss: "the cases are clear", description: "Reach 90% accuracy on a grammatical case, with at least 10 reviews of it.", icon: "Target" },
  { key: "perfect_session", title: "Laitmatu seanss", gloss: "a faultless session", description: "Finish a review session of 10+ cards with 100% recalled.", icon: "Trophy" },
  { key: "sprint_ace", title: "Kiire keel", gloss: "a quick tongue", description: "Score 15 or more in one 60-second Case Sprint.", icon: "Zap" },
  { key: "match_ace", title: "Paarid paigas", gloss: "the pairs are in place", description: "Clear a match round of 8 pairs in under 45 seconds.", icon: "Grid2x2" },
  { key: "unit_done", title: "Esimene peatükk", gloss: "first chapter", description: "Finish a unit on the learning path.", icon: "Map" },
  { key: "units_5", title: "Viis peatükki", gloss: "five chapters", description: "Finish five units on the learning path.", icon: "Map" },
  { key: "level_5", title: "Viies tase", gloss: "fifth level", description: "Reach level 5.", icon: "TrendingUp" },
  { key: "level_10", title: "Kümnes tase", gloss: "tenth level", description: "Reach level 10.", icon: "TrendingUp" },
  { key: "all_quests", title: "Päev tehtud", gloss: "the day is done", description: "Finish all three daily quests in one day.", icon: "CheckCheck" },
  { key: "early_bird", title: "Varajane lind", gloss: "early bird", description: "Review before 7am.", icon: "Sunrise" },
  { key: "night_owl", title: "Öökull", gloss: "night owl", description: "Review after 11pm.", icon: "Moon" },
];

const BADGE_BY_KEY = new Map(BADGES.map((b) => [b.key, b]));

export function badgeByKey(key: string): Badge | undefined {
  return BADGE_BY_KEY.get(key);
}

export interface BadgeStats {
  streak: number;
  totalReviews: number;
  cardsKnown: number;
  totalWords: number;
  /** The single highest-accuracy grammatical case with at least 10 reviews, if any. */
  bestCaseAccuracy: { grammCase: string; accuracy: number } | null;
  sprintBest: number;
  /** Best (lowest) time in seconds for a completed match round, 0 if never played. */
  matchBestSeconds: number;
  /** Units on the learning path whose every word has reached the Known state. */
  unitsCompleted: number;
  /** Current XP level. */
  level: number;
  /** Daily quests finished today. */
  questsDoneToday: number;
  /** The session that just ended, if this check runs at the end of one. */
  session?: { count: number; accuracy: number };
  /**
   * Local hours the session's reviews fall in, when a session has just ended.
   *
   * A list rather than one number, because the badges say "review before 7am"
   * and "review after 11pm" and a session has a beginning and an end. Reading
   * one moment denied the badge to somebody who sat down at half past six and
   * carried on past seven, which is the learner it is most obviously about.
   */
  reviewHours?: readonly number[];
}

/** Every badge key whose condition `stats` currently satisfies. */
export function earnedBadgeKeys(stats: BadgeStats): string[] {
  const earned: string[] = [];
  if (stats.totalReviews >= 1) earned.push("first_review");
  if (stats.streak >= 3) earned.push("streak_3");
  if (stats.streak >= 7) earned.push("streak_7");
  if (stats.streak >= 30) earned.push("streak_30");
  if (stats.streak >= 100) earned.push("streak_100");
  if (stats.totalReviews >= 100) earned.push("reviews_100");
  if (stats.totalReviews >= 500) earned.push("reviews_500");
  if (stats.totalReviews >= 1000) earned.push("reviews_1000");
  if (stats.cardsKnown >= 25) earned.push("cards_known_25");
  if (stats.cardsKnown >= 100) earned.push("cards_known_100");
  if (stats.totalWords >= 50) earned.push("deck_50");
  if (stats.totalWords >= 200) earned.push("deck_200");
  if (stats.bestCaseAccuracy && stats.bestCaseAccuracy.accuracy >= 90) earned.push("case_master");
  if (stats.session && stats.session.count >= 10 && stats.session.accuracy >= 100) earned.push("perfect_session");
  if (stats.sprintBest >= 15) earned.push("sprint_ace");
  if (stats.matchBestSeconds > 0 && stats.matchBestSeconds <= 45) earned.push("match_ace");
  if (stats.unitsCompleted >= 1) earned.push("unit_done");
  if (stats.unitsCompleted >= 5) earned.push("units_5");
  if (stats.level >= 5) earned.push("level_5");
  if (stats.level >= 10) earned.push("level_10");
  if (stats.questsDoneToday >= 3) earned.push("all_quests");
  if (stats.reviewHours?.some((hour) => hour < 7)) earned.push("early_bird");
  if (stats.reviewHours?.some((hour) => hour >= 23)) earned.push("night_owl");
  return earned;
}

/**
 * Consecutive-day streak from review timestamps, counting from today or yesterday.
 *
 * Days are the learner's own calendar days, not UTC ones and not the
 * deployment's: a streak that breaks at the wrong midnight is worse than no
 * streak at all. That is what `clock` carries, and it has to be passed by
 * anything running on a server, because the default reads whichever zone the
 * process happens to sit in. See lib/time/day.ts.
 */
export function computeStreak(
  dates: Date[],
  now: Date = new Date(),
  clock: DayClock = dayClock(),
): number {
  if (dates.length === 0) return 0;
  const days = new Set(dates.map((d) => clock.dayKey(d)));
  let streak = 0;
  let cursor = now;
  // Today not yet reviewed does not break a streak that is alive from yesterday.
  if (!days.has(clock.dayKey(cursor))) cursor = clock.shiftDay(cursor, 1);
  while (days.has(clock.dayKey(cursor))) {
    streak++;
    cursor = clock.shiftDay(cursor, 1);
  }
  return streak;
}

export interface StreakShieldResult {
  streak: number;
  /** Gap days bridged by a shield on *this* call — the caller persists these. */
  newlyShieldedDates: string[];
  /** Shields left after this call's newly-shielded days are spent. */
  shieldsRemaining: number;
}

/**
 * Like computeStreak, but a missed day is bridged by a streak shield instead
 * of breaking the streak — Duolingo's "streak freeze". Each shield covers
 * exactly one missed day; with several in stock, several missed days —
 * even consecutive ones — can each be bridged, until shields run out.
 *
 * `previouslyShieldedDates` are days a shield has already covered on an
 * earlier call; they count toward the streak like a real review and never
 * spend another shield. The walk back through history stops at the earliest
 * date `reviewDates` or `previouslyShieldedDates` actually knows about —
 * without that bound, an idle account with shields banked would have them
 * silently bridge years of pre-history that was never really a streak.
 */
export function computeStreakWithShields(
  reviewDates: readonly (Date | DayKey)[],
  shieldsAvailable: number,
  previouslyShieldedDates: string[] = [],
  now: Date = new Date(),
  clock: DayClock = dayClock(),
): StreakShieldResult {
  const reviewed = new Set(reviewDates.map((d) => (typeof d === "string" ? d : clock.dayKey(d))));
  const shielded = new Set(previouslyShieldedDates);
  const newlyShieldedDates: string[] = [];
  let shieldsLeft = shieldsAvailable;
  let streak = 0;

  // Lexicographic comparison works directly on YYYY-MM-DD strings.
  const known = [...reviewed, ...shielded];
  const earliestKnownDay = known.length > 0 ? known.reduce((a, b) => (a < b ? a : b)) : null;

  let cursor = now;
  const today = clock.dayKey(cursor);
  // Today not yet reviewed does not break a streak that is alive from yesterday.
  if (!reviewed.has(today) && !shielded.has(today)) cursor = clock.shiftDay(cursor, 1);

  for (;;) {
    const day = clock.dayKey(cursor);
    if (earliestKnownDay === null || day < earliestKnownDay) break;
    if (reviewed.has(day) || shielded.has(day)) {
      streak++;
    } else if (shieldsLeft > 0) {
      shieldsLeft--;
      newlyShieldedDates.push(day);
      streak++;
    } else {
      break;
    }
    cursor = clock.shiftDay(cursor, 1);
  }

  return { streak, newlyShieldedDates, shieldsRemaining: shieldsLeft };
}
