/**
 * Achievement definitions and the pure logic that decides which are earned.
 *
 * Framework-free, like lib/estonian/ and lib/srs/ — every badge condition is a
 * deterministic function of stats pulled from the database, never of anything
 * generated by the AI tutor (ADR-005 does not apply here, but the same instinct
 * does: a badge is either honestly earned from real review history or it isn't).
 */

export interface Badge {
  key: string;
  title: string;
  description: string;
  /** Name of a lucide-react icon component; mapped to the real component in the UI. */
  icon: string;
}

export const BADGES: Badge[] = [
  { key: "first_review", title: "Esimene samm", description: "Complete your first review.", icon: "Sparkles" },
  { key: "streak_3", title: "Kolm järjest", description: "Reach a 3-day streak.", icon: "Flame" },
  { key: "streak_7", title: "Terve nädal", description: "Reach a 7-day streak.", icon: "Flame" },
  { key: "streak_30", title: "Terve kuu", description: "Reach a 30-day streak.", icon: "Flame" },
  { key: "streak_100", title: "Sada päeva", description: "Reach a 100-day streak.", icon: "Flame" },
  { key: "reviews_100", title: "Sada kordust", description: "Complete 100 reviews in total.", icon: "Repeat" },
  { key: "reviews_500", title: "Viissada kordust", description: "Complete 500 reviews in total.", icon: "Repeat" },
  { key: "reviews_1000", title: "Tuhat kordust", description: "Complete 1,000 reviews in total.", icon: "Repeat" },
  { key: "cards_known_25", title: "Veerandsada teada", description: "Get 25 cards into the Known state.", icon: "BookCheck" },
  { key: "cards_known_100", title: "Sada teada", description: "Get 100 cards into the Known state.", icon: "BookCheck" },
  { key: "deck_50", title: "Viiskümmend sõna", description: "Add 50 words to your dictionary.", icon: "Library" },
  { key: "deck_200", title: "Kakssada sõna", description: "Add 200 words to your dictionary.", icon: "Library" },
  { key: "case_master", title: "Käänded selged", description: "Reach 90% accuracy on a grammatical case, with at least 10 reviews of it.", icon: "Target" },
  { key: "perfect_session", title: "Laitmatu seanss", description: "Finish a review session of 10+ cards with 100% recalled.", icon: "Trophy" },
  { key: "sprint_ace", title: "Kiire keel", description: "Score 15 or more in one 60-second Case Sprint.", icon: "Zap" },
];

const BADGE_BY_KEY = new Map(BADGES.map((b) => [b.key, b]));

export function badgeByKey(key: string): Badge | undefined {
  return BADGE_BY_KEY.get(key);
}

export interface BadgeStats {
  streak: number;
  totalReviews: number;
  cardsKnown: number;
  totalWords: number;
  /** The single highest-accuracy grammatical case with at least 10 reviews, if any. */
  bestCaseAccuracy: { grammCase: string; accuracy: number } | null;
  sprintBest: number;
  /** The session that just ended, if this check runs at the end of one. */
  session?: { count: number; accuracy: number };
}

/** Every badge key whose condition `stats` currently satisfies. */
export function earnedBadgeKeys(stats: BadgeStats): string[] {
  const earned: string[] = [];
  if (stats.totalReviews >= 1) earned.push("first_review");
  if (stats.streak >= 3) earned.push("streak_3");
  if (stats.streak >= 7) earned.push("streak_7");
  if (stats.streak >= 30) earned.push("streak_30");
  if (stats.streak >= 100) earned.push("streak_100");
  if (stats.totalReviews >= 100) earned.push("reviews_100");
  if (stats.totalReviews >= 500) earned.push("reviews_500");
  if (stats.totalReviews >= 1000) earned.push("reviews_1000");
  if (stats.cardsKnown >= 25) earned.push("cards_known_25");
  if (stats.cardsKnown >= 100) earned.push("cards_known_100");
  if (stats.totalWords >= 50) earned.push("deck_50");
  if (stats.totalWords >= 200) earned.push("deck_200");
  if (stats.bestCaseAccuracy && stats.bestCaseAccuracy.accuracy >= 90) earned.push("case_master");
  if (stats.session && stats.session.count >= 10 && stats.session.accuracy >= 100) earned.push("perfect_session");
  if (stats.sprintBest >= 15) earned.push("sprint_ace");
  return earned;
}

/** Consecutive-day streak from review timestamps, counting from today or yesterday. */
export function computeStreak(dates: Date[]): number {
  if (dates.length === 0) return 0;
  const days = new Set(dates.map((d) => d.toISOString().slice(0, 10)));
  let streak = 0;
  const cursor = new Date();
  // Today not yet reviewed does not break a streak that is alive from yesterday.
  if (!days.has(cursor.toISOString().slice(0, 10))) cursor.setDate(cursor.getDate() - 1);
  while (days.has(cursor.toISOString().slice(0, 10))) {
    streak++;
    cursor.setDate(cursor.getDate() - 1);
  }
  return streak;
}
