/**
 * Achievement definitions and the pure logic that decides which are earned.
 *
 * Framework-free, like lib/estonian/ and lib/srs/ — every badge condition is a
 * deterministic function of stats pulled from the database, never of anything
 * generated by the AI tutor (ADR-005 does not apply here, but the same instinct
 * does: a badge is either honestly earned from real review history or it isn't).
 */

import { dayKey, shiftDay } from "@/lib/time/day";

export interface Badge {
  key: string;
  title: string;
  description: string;
  /** Name of a lucide-react icon component; mapped to the real component in the UI. */
  icon: string;
}

export const BADGES: Badge[] = [
  { key: "first_review", title: "Esimene samm", description: "Complete your first review.", icon: "Sparkles" },
  { key: "streak_3", title: "Kolm järjest", description: "Reach a 3-day streak.", icon: "Flame" },
  { key: "streak_7", title: "Terve nädal", description: "Reach a 7-day streak.", icon: "Flame" },
  { key: "streak_30", title: "Terve kuu", description: "Reach a 30-day streak.", icon: "Flame" },
  { key: "streak_100", title: "Sada päeva", description: "Reach a 100-day streak.", icon: "Flame" },
  { key: "reviews_100", title: "Sada kordust", description: "Complete 100 reviews in total.", icon: "Repeat" },
  { key: "reviews_500", title: "Viissada kordust", description: "Complete 500 reviews in total.", icon: "Repeat" },
  { key: "reviews_1000", title: "Tuhat kordust", description: "Complete 1,000 reviews in total.", icon: "Repeat" },
  { key: "cards_known_25", title: "Veerandsada teada", description: "Get 25 cards into the Known state.", icon: "BookCheck" },
  { key: "cards_known_100", title: "Sada teada", description: "Get 100 cards into the Known state.", icon: "BookCheck" },
  { key: "deck_50", title: "Viiskümmend sõna", description: "Add 50 words to your dictionary.", icon: "Library" },
  { key: "deck_200", title: "Kakssada sõna", description: "Add 200 words to your dictionary.", icon: "Library" },
  { key: "case_master", title: "Käänded selged", description: "Reach 90% accuracy on a grammatical case, with at least 10 reviews of it.", icon: "Target" },
  { key: "perfect_session", title: "Laitmatu seanss", description: "Finish a review session of 10+ cards with 100% recalled.", icon: "Trophy" },
  { key: "sprint_ace", title: "Kiire keel", description: "Score 15 or more in one 60-second Case Sprint.", icon: "Zap" },
  { key: "match_ace", title: "Paarid paigas", description: "Clear a match round of 8 pairs in under 45 seconds.", icon: "Grid2x2" },
  { key: "unit_done", title: "Esimene peatükk", description: "Finish a unit on the learning path.", icon: "Map" },
  { key: "units_5", title: "Viis peatükki", description: "Finish five units on the learning path.", icon: "Map" },
  { key: "level_5", title: "Viies tase", description: "Reach level 5.", icon: "TrendingUp" },
  { key: "level_10", title: "Kümnes tase", description: "Reach level 10.", icon: "TrendingUp" },
  { key: "all_quests", title: "Päev tehtud", description: "Finish all three daily quests in one day.", icon: "CheckCheck" },
  { key: "early_bird", title: "Varajane lind", description: "Review before 7am.", icon: "Sunrise" },
  { key: "night_owl", title: "Öökull", description: "Review after 11pm.", icon: "Moon" },
];

const BADGE_BY_KEY = new Map(BADGES.map((b) => [b.key, b]));

export function badgeByKey(key: string): Badge | undefined {
  return BADGE_BY_KEY.get(key);
}

export interface BadgeStats {
  streak: number;
  totalReviews: number;
  cardsKnown: number;
  totalWords: number;
  /** The single highest-accuracy grammatical case with at least 10 reviews, if any. */
  bestCaseAccuracy: { grammCase: string; accuracy: number } | null;
  sprintBest: number;
  /** Best (lowest) time in seconds for a completed match round, 0 if never played. */
  matchBestSeconds: number;
  /** Units on the learning path whose every word has reached the Known state. */
  unitsCompleted: number;
  /** Current XP level. */
  level: number;
  /** Daily quests finished today. */
  questsDoneToday: number;
  /** The session that just ended, if this check runs at the end of one. */
  session?: { count: number; accuracy: number };
  /** Local hour a review happened at, when this check runs right after one. */
  reviewHour?: number;
}

/** Every badge key whose condition `stats` currently satisfies. */
export function earnedBadgeKeys(stats: BadgeStats): string[] {
  const earned: string[] = [];
  if (stats.totalReviews >= 1) earned.push("first_review");
  if (stats.streak >= 3) earned.push("streak_3");
  if (stats.streak >= 7) earned.push("streak_7");
  if (stats.streak >= 30) earned.push("streak_30");
  if (stats.streak >= 100) earned.push("streak_100");
  if (stats.totalReviews >= 100) earned.push("reviews_100");
  if (stats.totalReviews >= 500) earned.push("reviews_500");
  if (stats.totalReviews >= 1000) earned.push("reviews_1000");
  if (stats.cardsKnown >= 25) earned.push("cards_known_25");
  if (stats.cardsKnown >= 100) earned.push("cards_known_100");
  if (stats.totalWords >= 50) earned.push("deck_50");
  if (stats.totalWords >= 200) earned.push("deck_200");
  if (stats.bestCaseAccuracy && stats.bestCaseAccuracy.accuracy >= 90) earned.push("case_master");
  if (stats.session && stats.session.count >= 10 && stats.session.accuracy >= 100) earned.push("perfect_session");
  if (stats.sprintBest >= 15) earned.push("sprint_ace");
  if (stats.matchBestSeconds > 0 && stats.matchBestSeconds <= 45) earned.push("match_ace");
  if (stats.unitsCompleted >= 1) earned.push("unit_done");
  if (stats.unitsCompleted >= 5) earned.push("units_5");
  if (stats.level >= 5) earned.push("level_5");
  if (stats.level >= 10) earned.push("level_10");
  if (stats.questsDoneToday >= 3) earned.push("all_quests");
  if (stats.reviewHour !== undefined && stats.reviewHour < 7) earned.push("early_bird");
  if (stats.reviewHour !== undefined && stats.reviewHour >= 23) earned.push("night_owl");
  return earned;
}

/**
 * Consecutive-day streak from review timestamps, counting from today or yesterday.
 *
 * Days are the learner's own calendar days (lib/time/day.ts), not UTC ones — a
 * streak that breaks at the wrong midnight is worse than no streak at all.
 */
export function computeStreak(dates: Date[], now: Date = new Date()): number {
  if (dates.length === 0) return 0;
  const days = new Set(dates.map((d) => dayKey(d)));
  let streak = 0;
  let cursor = now;
  // Today not yet reviewed does not break a streak that is alive from yesterday.
  if (!days.has(dayKey(cursor))) cursor = shiftDay(cursor, 1);
  while (days.has(dayKey(cursor))) {
    streak++;
    cursor = shiftDay(cursor, 1);
  }
  return streak;
}

export interface StreakShieldResult {
  streak: number;
  /** Gap days bridged by a shield on *this* call — the caller persists these. */
  newlyShieldedDates: string[];
  /** Shields left after this call's newly-shielded days are spent. */
  shieldsRemaining: number;
}

/**
 * Like computeStreak, but a missed day is bridged by a streak shield instead
 * of breaking the streak — Duolingo's "streak freeze". Each shield covers
 * exactly one missed day; with several in stock, several missed days —
 * even consecutive ones — can each be bridged, until shields run out.
 *
 * `previouslyShieldedDates` are days a shield has already covered on an
 * earlier call; they count toward the streak like a real review and never
 * spend another shield. The walk back through history stops at the earliest
 * date `reviewDates` or `previouslyShieldedDates` actually knows about —
 * without that bound, an idle account with shields banked would have them
 * silently bridge years of pre-history that was never really a streak.
 */
export function computeStreakWithShields(
  reviewDates: Date[],
  shieldsAvailable: number,
  previouslyShieldedDates: string[] = [],
  now: Date = new Date(),
): StreakShieldResult {
  const reviewed = new Set(reviewDates.map((d) => dayKey(d)));
  const shielded = new Set(previouslyShieldedDates);
  const newlyShieldedDates: string[] = [];
  let shieldsLeft = shieldsAvailable;
  let streak = 0;

  // Lexicographic comparison works directly on YYYY-MM-DD strings.
  const known = [...reviewed, ...shielded];
  const earliestKnownDay = known.length > 0 ? known.reduce((a, b) => (a < b ? a : b)) : null;

  let cursor = now;
  const today = dayKey(cursor);
  // Today not yet reviewed does not break a streak that is alive from yesterday.
  if (!reviewed.has(today) && !shielded.has(today)) cursor = shiftDay(cursor, 1);

  for (;;) {
    const day = dayKey(cursor);
    if (earliestKnownDay === null || day < earliestKnownDay) break;
    if (reviewed.has(day) || shielded.has(day)) {
      streak++;
    } else if (shieldsLeft > 0) {
      shieldsLeft--;
      newlyShieldedDates.push(day);
      streak++;
    } else {
      break;
    }
    cursor = shiftDay(cursor, 1);
  }

  return { streak, newlyShieldedDates, shieldsRemaining: shieldsLeft };
}
