import { describe, expect, it } from "vitest";
import { WORD_EMOJI } from "./emoji";
import { SCENES, SCENE_LEMMAS, sceneById, sceneLevel } from "./scenes";
import { findTells } from "@/lib/copy/voice";

/**
 * A scene names words; the dictionary decides whether they exist.
 *
 * The same arrangement `syllabus.test.ts` has with the Ekilex harvest, one
 * layer in: `WORD_EMOJI` is generated by joining Unicode's data file against
 * the dictionary, so a lemma this file finds there is a word with an entry and
 * a picture both. A misspelling here cannot reach a learner, it can only fail
 * this, loudly.
 */
describe("the scene table", () => {
  it("names only words the emoji join brought back", () => {
    const missing = SCENE_LEMMAS.filter((lemma) => !WORD_EMOJI[lemma]);
    expect(missing).toEqual([]);
  });

  it("gives every scene three different words", () => {
    for (const scene of SCENES) {
      expect(scene.lemmas).toHaveLength(3);
      expect(new Set(scene.lemmas).size, scene.id).toBe(3);
    }
  });

  it("keeps every id unique, since a contributed sentence attaches to one", () => {
    const ids = SCENES.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("uses ids that are English slugs rather than words", () => {
    for (const scene of SCENES) {
      expect(scene.id, scene.id).toMatch(/^[a-z][a-z0-9-]*$/);
    }
  });

  it("writes no Estonian outside the lemma requests", () => {
    /*
      The situation is the only prose in the file and it is English. Estonian's
      own letters are the cheap half of the check; the other half is that a
      situation is short enough to be a heading rather than a sentence, because
      a sentence here would be somebody describing the picture for the learner,
      which is the exercise.
    */
    for (const scene of SCENES) {
      expect(scene.situation, scene.id).not.toMatch(/[õäöüšž]/i);
      expect(scene.situation.length, scene.id).toBeLessThanOrEqual(24);
      expect(findTells(scene.situation), scene.id).toEqual([]);
    }
  });

  it("is worth generating a template for", () => {
    // Sixty is the argument in the header: bounded enough to ask somebody for
    // a sentence each, wide enough that a round of five does not repeat.
    expect(SCENES.length).toBeGreaterThanOrEqual(40);
  });

  it("finds a scene by its id", () => {
    expect(sceneById("breakfast")?.situation).toBe("Breakfast");
    expect(sceneById("no-such-scene")).toBeUndefined();
  });
});

describe("sceneLevel", () => {
  it("is the hardest word in it", () => {
    expect(sceneLevel(["A1", "B1", "A2"])).toBe("B1");
    expect(sceneLevel(["A1", "A1", "A1"])).toBe("A1");
  });

  it("refuses to band a scene holding a word the dictionary could not band", () => {
    expect(sceneLevel(["A1", null, "A2"])).toBeNull();
    expect(sceneLevel([])).toBeNull();
  });
});
