import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

/*
  THE HEADWORD LIST, CHECKED AS DATA.

  `prisma/data/wordlist.txt` is generated by `scripts/build-wordlist.ts` from
  thirty-two Ekilex requests and is the only thing standing between a learner
  and "nothing found" for most of the Estonian language. It is generated, so
  nobody reads it; what a test can do is notice when it has quietly become
  something else, which for a generated file is the failure that goes unseen.

  Cheap: one read of a 1.8MB file, no database and no network.
*/
const WORDS = readFileSync("prisma/data/wordlist.txt", "utf8")
  .split("\n").map((l) => l.trim()).filter(Boolean);

describe("the Estonian headword list", () => {
  it("holds most of the language rather than a sample of it", () => {
    /*
      A floor rather than an exact count, because Ekilex is a living database
      and the number moves. Well under the 154,995 the first run produced and
      far above anything a truncated or half-written file would reach: a
      generated file that silently became a fragment is what this notices.
    */
    expect(WORDS.length).toBeGreaterThan(120_000);
  });

  it("holds the word whose absence started this", () => {
    // Reported as "I searched for uudishimulik, which is used within our
    // website, on our website dictionary and it wasn't there. Feels bad."
    expect(WORDS).toContain("uudishimulik");
  });

  it("holds ordinary words a beginner would type", () => {
    for (const word of ["tuba", "kohv", "raamat", "tervis", "jalgratas", "rõõmus"]) {
      expect(WORDS, `${word} is missing from the headword list`).toContain(word);
    }
  });

  it("is only Estonian words, in the shape the search compares", () => {
    /*
      Lowercase, letters and an internal hyphen. The builder filters to this and
      the filter is the half worth pinning: without it the list carries `AS`,
      `A` and every two-letter abbreviation in the term bases, and then every
      typo looks like a word and the "did you mean" row offers nonsense.
    */
    const wrong = WORDS.filter((w) => !/^[a-zäöüõšž]+(-[a-zäöüõšž]+)*$/.test(w));
    expect(wrong.slice(0, 10)).toEqual([]);
  });

  it("names each word once", () => {
    expect(new Set(WORDS).size).toBe(WORDS.length);
  });

  it("is sorted, so a re-run is a diff rather than a reshuffle", () => {
    const sorted = [...WORDS].sort((a, b) => a.localeCompare(b, "et"));
    expect(WORDS.slice(0, 500)).toEqual(sorted.slice(0, 500));
  });
});
