/**
 * A1 — from nothing to getting by.
 *
 * The level is deliberately front-loaded with concrete, pointable nouns and the
 * fourteen verbs an Estonian sentence cannot avoid. Grammar arrives as it is
 * needed rather than as a syllabus of its own: the partitive turns up in the
 * food unit because that is where a learner first meets it, and the inessive in
 * the home unit because a room is the easiest thing to be inside of.
 */
import { unit } from "./types";

export const A1 = [
  unit({
    id: "tervitused",
    title: "Tervitused",
    subtitle: "Greetings and getting by",
    icon: "Hand",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Greet someone, thank them, apologise, and say you do not understand.",
    blurb: "The twenty phrases that get you through a first conversation without grammar.",
    grammar: ["politeness"],
    cardTypes: ["RECOGNITION", "PRODUCTION"],
    words: [
      ["Tere!", "Hello!", "PHRASE"],
      ["Tere hommikust!", "Good morning!", "PHRASE"],
      ["Head aega!", "Goodbye!", "PHRASE"],
      ["Nägemist!", "See you!", "PHRASE"],
      ["Aitäh!", "Thank you!", "PHRASE"],
      ["Palun", "Please / You're welcome", "PHRASE"],
      ["Vabandust!", "Sorry! / Excuse me!", "PHRASE"],
      ["Kuidas läheb?", "How's it going?", "PHRASE"],
      ["Ma ei saa aru", "I don't understand", "PHRASE"],
      ["Kas sa räägid inglise keelt?", "Do you speak English?", "PHRASE"],
      ["Ma õpin eesti keelt", "I am learning Estonian", "PHRASE"],
      ["Mis kell on?", "What time is it?", "PHRASE"],
      ["Kui palju see maksab?", "How much does it cost?", "PHRASE"],
      ["Mulle meeldib see", "I like it", "PHRASE"],
      ["Head isu!", "Enjoy your meal!", "PHRASE"],
      ["Palju õnne!", "Congratulations!", "PHRASE"],
      ["Mul on hea meel", "I'm glad", "PHRASE"],
      ["Ma ei tea veel", "I don't know yet", "PHRASE"],
    ],
  }),

  unit({
    id: "inimesed",
    title: "Inimesed",
    subtitle: "People and family",
    icon: "Users",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Say who is in your family and introduce the people around you.",
    blurb: "Who is in the room. Also your first gradation: sõber : sõbra.",
    grammar: ["nominative", "genitive", "gradation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["tervitused"],
    words: [
      ["inimene", "person, human"],
      ["naine", "woman, wife"],
      ["mees", "man, husband"],
      ["laps", "child"],
      ["sõber", "friend"],
      ["ema", "mother"],
      ["isa", "father"],
      ["pere", "family"],
      ["vend", "brother"],
      ["õde", "sister"],
      ["tütar", "daughter"],
      ["poeg", "son"],
      ["vanaema", "grandmother", "NOUN"],
      ["vanaisa", "grandfather"],
      ["nimi", "name"],
      ["õpetaja", "teacher"],
      ["õpilane", "pupil, student"],
      ["arst", "doctor"],
    ],
  }),

  unit({
    id: "arvud",
    title: "Arvud",
    subtitle: "Numbers and counting",
    icon: "Hash",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Count, give your phone number, say a price and tell someone your age.",
    blurb: "Counting is where the partitive first bites: kaks raamatut, not kaks raamat.",
    grammar: ["numerals", "partitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["inimesed"],
    words: [
      ["number", "number"],
      ["üks", "one"],
      ["kaks", "two"],
      ["kolm", "three"],
      ["neli", "four"],
      ["viis", "five"],
      ["kuus", "six"],
      ["seitse", "seven"],
      ["kaheksa", "eight"],
      ["üheksa", "nine"],
      ["kümme", "ten"],
      ["sada", "hundred"],
      ["tuhat", "thousand"],
      ["esimene", "first", "ADJECTIVE"],
      ["teine", "second, other", "ADJECTIVE"],
      ["pool", "half"],
    ],
  }),

  unit({
    id: "kodu",
    title: "Kodu",
    subtitle: "Home and everyday objects",
    icon: "House",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Describe your home and say where things are in it.",
    blurb: "Things you can point at, the easiest place to meet the inessive (toas, köögis).",
    grammar: ["inessive", "nominative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["inimesed"],
    words: [
      ["kodu", "home"],
      ["maja", "house"],
      ["tuba", "room"],
      ["köök", "kitchen"],
      ["korter", "flat, apartment"],
      ["uks", "door"],
      ["aken", "window"],
      ["laud", "table"],
      ["tool", "chair"],
      ["voodi", "bed"],
      ["raamat", "book"],
      ["arvuti", "computer"],
      ["telefon", "telephone"],
      ["võti", "key"],
      ["klaas", "glass"],
      ["tass", "cup"],
      ["pilt", "picture"],
      ["sein", "wall"],
      ["põrand", "floor"],
    ],
  }),

  unit({
    id: "sook-ja-jook",
    title: "Söök ja jook",
    subtitle: "Food and drink",
    icon: "Utensils",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Order food, shop for groceries and say what you like to eat.",
    blurb: "Enough to order, shop and read a menu. The partitive lives here (ma joon kohvi).",
    grammar: ["partitive", "object"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kodu"],
    words: [
      ["toit", "food"],
      ["söök", "food, a meal"],
      ["jook", "drink"],
      ["leib", "bread (dark)"],
      ["sai", "bread (white)"],
      ["kohv", "coffee"],
      ["vesi", "water"],
      ["piim", "milk"],
      ["mahl", "juice"],
      ["liha", "meat"],
      ["kala", "fish"],
      ["õun", "apple"],
      ["kartul", "potato"],
      ["juust", "cheese"],
      ["muna", "egg"],
      ["või", "butter"],
      ["sool", "salt"],
      ["suhkur", "sugar"],
      ["supp", "soup"],
    ],
  }),

  unit({
    id: "aeg",
    title: "Aeg",
    subtitle: "Days, hours and when things happen",
    icon: "Clock",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Tell the time, name the days, and say when something happens.",
    blurb: "Time words carry the adessive and elative constantly, hommikul, esmaspäevast.",
    grammar: ["adessive", "elative", "time-expressions"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["arvud"],
    words: [
      ["aeg", "time"],
      ["päev", "day"],
      ["öö", "night"],
      ["hommik", "morning"],
      ["õhtu", "evening"],
      ["nädal", "week"],
      ["kuu", "month, moon"],
      ["aasta", "year"],
      ["tund", "hour, lesson"],
      ["minut", "minute"],
      ["kell", "clock, o'clock"],
      ["esmaspäev", "Monday"],
      ["teisipäev", "Tuesday"],
      ["kolmapäev", "Wednesday"],
      ["neljapäev", "Thursday"],
      ["reede", "Friday"],
      ["laupäev", "Saturday"],
      ["pühapäev", "Sunday"],
    ],
  }),

  unit({
    id: "pohiverbid",
    title: "Põhiverbid",
    subtitle: "The irregular core",
    icon: "Zap",
    level: "A1",
    module: "Tegevused",
    canDo: "Build a simple sentence in the present tense about what you do.",
    blurb: "Verbs that break the rules and are used constantly. Learn these as forms, not patterns.",
    grammar: ["present-tense", "olema", "negation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["kodu"],
    words: [
      ["olema", "to be"],
      ["minema", "to go"],
      ["tulema", "to come"],
      ["tegema", "to do, to make"],
      ["saama", "to get, to become"],
      ["pidama", "to have to, to keep"],
      ["sööma", "to eat"],
      ["jooma", "to drink"],
      ["tooma", "to bring"],
      ["viima", "to take away"],
      ["andma", "to give"],
      ["võtma", "to take"],
      ["panema", "to put"],
      ["jääma", "to stay, to remain"],
    ],
  }),

  unit({
    id: "iga-paev",
    title: "Iga päev",
    subtitle: "Everyday actions",
    icon: "Footprints",
    level: "A1",
    module: "Tegevused",
    canDo: "Describe your daily routine from waking up to going to bed.",
    blurb: "What you do all day, in the two infinitives Estonian actually uses.",
    grammar: ["present-tense", "infinitives"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["pohiverbid"],
    words: [
      ["tahtma", "to want"],
      ["teadma", "to know (a fact)"],
      ["tundma", "to know (a person), to feel"],
      ["nägema", "to see"],
      ["kuulma", "to hear"],
      ["rääkima", "to speak"],
      ["ütlema", "to say"],
      ["küsima", "to ask"],
      ["vastama", "to answer"],
      ["lugema", "to read, to count"],
      ["kirjutama", "to write"],
      ["õppima", "to learn, to study"],
      ["töötama", "to work"],
      ["elama", "to live"],
      ["magama", "to sleep"],
      ["ärkama", "to wake up"],
      ["istuma", "to sit"],
      ["seisma", "to stand"],
    ],
  }),

  unit({
    id: "omadussonad",
    title: "Omadussõnad",
    subtitle: "Describing things",
    icon: "Palette",
    level: "A1",
    module: "Kirjeldamine",
    canDo: "Describe a thing or a person with an adjective that agrees with it.",
    blurb: "Adjectives agree with their noun in Estonian, so every one you learn pays for itself.",
    grammar: ["adjective-agreement", "nominative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kodu"],
    words: [
      ["suur", "big, large", "ADJECTIVE"],
      ["väike", "small", "ADJECTIVE"],
      ["hea", "good", "ADJECTIVE"],
      ["halb", "bad", "ADJECTIVE"],
      ["uus", "new", "ADJECTIVE"],
      ["vana", "old", "ADJECTIVE"],
      ["noor", "young", "ADJECTIVE"],
      ["pikk", "long, tall", "ADJECTIVE"],
      ["lühike", "short", "ADJECTIVE"],
      ["kiire", "fast, quick", "ADJECTIVE"],
      ["aeglane", "slow", "ADJECTIVE"],
      ["kallis", "expensive, dear", "ADJECTIVE"],
      ["odav", "cheap", "ADJECTIVE"],
      ["ilus", "beautiful", "ADJECTIVE"],
      ["tore", "nice, lovely", "ADJECTIVE"],
      ["raske", "difficult, heavy", "ADJECTIVE"],
      ["kerge", "easy, light", "ADJECTIVE"],
      ["lihtne", "simple", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "varvid",
    title: "Värvid",
    subtitle: "Colours",
    icon: "Paintbrush",
    level: "A1",
    module: "Kirjeldamine",
    canDo: "Name colours and describe what something looks like.",
    blurb: "Short, concrete, and every one of them declines like an ordinary adjective.",
    grammar: ["adjective-agreement"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["omadussonad"],
    words: [
      ["värv", "colour"],
      ["punane", "red", "ADJECTIVE"],
      ["sinine", "blue", "ADJECTIVE"],
      ["roheline", "green", "ADJECTIVE"],
      ["kollane", "yellow", "ADJECTIVE"],
      ["must", "black", "ADJECTIVE"],
      ["valge", "white", "ADJECTIVE"],
      ["hall", "grey", "ADJECTIVE"],
      ["pruun", "brown", "ADJECTIVE"],
      ["roosa", "pink", "ADJECTIVE"],
      ["lilla", "purple", "ADJECTIVE"],
      ["hele", "light, pale", "ADJECTIVE"],
      ["tume", "dark", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "riided",
    title: "Riided",
    subtitle: "Clothes and what you wear",
    icon: "Shirt",
    level: "A1",
    module: "Kirjeldamine",
    canDo: "Say what you are wearing and shop for clothes by size and colour.",
    blurb: "A shop conversation you will have in your first week, and a pile of easy nouns.",
    grammar: ["adjective-agreement", "partitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["varvid"],
    words: [
      ["särk", "shirt"],
      ["kleit", "dress"],
      ["seelik", "skirt"],
      ["king", "shoe"],
      ["sokk", "sock"],
      ["müts", "hat"],
      ["mantel", "coat"],
      ["jope", "jacket"],
      ["sall", "scarf"],
      ["kinnas", "glove"],
      ["taskurätik", "handkerchief"],
      ["vöö", "belt"],
      ["riie", "cloth, fabric"],
    ],
  }),

  unit({
    id: "ilm",
    title: "Ilm",
    subtitle: "Weather",
    icon: "CloudSun",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Talk about the weather, which in Estonia is never small talk for long.",
    blurb: "Half of every Estonian conversation opens here, and the vocabulary is tiny.",
    grammar: ["olema", "adjective-agreement"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["omadussonad"],
    words: [
      ["ilm", "weather"],
      ["päike", "sun"],
      ["vihm", "rain"],
      ["lumi", "snow"],
      ["tuul", "wind"],
      ["pilv", "cloud"],
      ["torm", "storm"],
      ["jää", "ice"],
      ["udu", "fog"],
      ["kraad", "degree"],
      ["külm", "cold", "ADJECTIVE"],
      ["soe", "warm", "ADJECTIVE"],
      ["kuum", "hot", "ADJECTIVE"],
      ["märg", "wet", "ADJECTIVE"],
      ["kuiv", "dry", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "ostmine",
    title: "Poes ja tänaval",
    subtitle: "Shopping and getting around",
    icon: "ShoppingBag",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Buy something, ask the price, and find your way to a place in town.",
    blurb: "Buying, paying, going. Verbs and places together, because that is how they turn up.",
    grammar: ["partitive", "illative", "allative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["sook-ja-jook", "arvud"],
    words: [
      ["pood", "shop"],
      ["turg", "market"],
      ["raha", "money"],
      ["hind", "price"],
      ["pilet", "ticket"],
      ["ostma", "to buy"],
      ["müüma", "to sell"],
      ["maksma", "to pay, to cost"],
      ["linn", "town, city"],
      ["tänav", "street"],
      ["tee", "road, tea"],
      ["buss", "bus"],
      ["rong", "train"],
      ["auto", "car"],
      ["jaam", "station"],
      ["park", "park"],
    ],
  }),

  unit({
    id: "kus-ja-kuhu",
    title: "Kus ja kuhu",
    subtitle: "Places and directions",
    icon: "Map",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Ask where something is and understand the directions you are given.",
    blurb: "Estonian answers 'where' and 'where to' with different cases. This is that split.",
    grammar: ["inessive", "illative", "elative", "allative", "adessive", "ablative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["ostmine", "kodu"],
    words: [
      ["koht", "place"],
      ["kesklinn", "town centre"],
      ["väljak", "square"],
      ["sild", "bridge"],
      ["nurk", "corner"],
      ["kool", "school"],
      ["töö", "work"],
      ["haigla", "hospital"],
      ["kirik", "church"],
      ["rand", "beach"],
      ["ülikool", "university"],
      ["kohvik", "café"],
      ["restoran", "restaurant"],
      ["hotell", "hotel"],
    ],
  }),
] as const;
