/**
 * A1 — from nothing to getting by.
 *
 * The level is deliberately front-loaded with concrete, pointable nouns and the
 * fourteen verbs an Estonian sentence cannot avoid. Grammar arrives as it is
 * needed rather than as a syllabus of its own: the partitive turns up in the
 * food unit because that is where a learner first meets it, and the inessive in
 * the home unit because a room is the easiest thing to be inside of.
 */
import { unit } from "./types";

export const A1 = [
  unit({
    id: "tervitused",
    title: "Tervitused",
    subtitle: "Greetings and getting by",
    icon: "Hand",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Greet someone, thank them, apologise, and say you do not understand.",
    blurb: "The twenty phrases that get you through a first conversation without grammar.",
    grammar: ["politeness"],
    cardTypes: ["RECOGNITION", "PRODUCTION"],
    words: [
      ["Tere!", "Hello!", "PHRASE"],
      ["Tere hommikust!", "Good morning!", "PHRASE"],
      ["Head aega!", "Goodbye!", "PHRASE"],
      ["Nägemist!", "See you!", "PHRASE"],
      ["Aitäh!", "Thank you!", "PHRASE"],
      ["Palun", "Please / You're welcome", "PHRASE"],
      ["Vabandust!", "Sorry! / Excuse me!", "PHRASE"],
      ["Kuidas läheb?", "How's it going?", "PHRASE"],
      ["Ma ei saa aru", "I don't understand", "PHRASE"],
      ["Kas sa räägid inglise keelt?", "Do you speak English?", "PHRASE"],
      ["Ma õpin eesti keelt", "I am learning Estonian", "PHRASE"],
      ["Mis kell on?", "What time is it?", "PHRASE"],
      ["Kui palju see maksab?", "How much does it cost?", "PHRASE"],
      ["Mulle meeldib see", "I like it", "PHRASE"],
      ["Head isu!", "Enjoy your meal!", "PHRASE"],
      ["Palju õnne!", "Congratulations!", "PHRASE"],
      ["Mul on hea meel", "I'm glad", "PHRASE"],
      ["Ma ei tea veel", "I don't know yet", "PHRASE"],
    ],
  }),

  unit({
    id: "inimesed",
    title: "Inimesed",
    subtitle: "People and family",
    icon: "Users",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Say who is in your family and introduce the people around you.",
    blurb: "Who is in the room. Also your first gradation: sõber : sõbra.",
    grammar: ["nominative", "genitive", "gradation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["tervitused"],
    words: [
      ["inimene", "person, human"],
      ["naine", "woman, wife"],
      ["mees", "man, husband"],
      ["laps", "child"],
      ["sõber", "friend"],
      ["ema", "mother"],
      ["isa", "father"],
      ["pere", "family"],
      ["vend", "brother"],
      ["õde", "sister"],
      ["tütar", "daughter"],
      ["poeg", "son"],
      ["vanaema", "grandmother", "NOUN"],
      ["vanaisa", "grandfather"],
      ["nimi", "name"],
      ["õpetaja", "teacher"],
      ["õpilane", "pupil, student"],
      ["arst", "doctor"],
    ],
  }),

  unit({
    id: "arvud",
    title: "Arvud",
    subtitle: "Numbers and counting",
    icon: "Hash",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Count, give your phone number, say a price and tell someone your age.",
    blurb: "Counting is where the partitive first bites: kaks raamatut, not kaks raamat.",
    grammar: ["numerals", "partitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["inimesed"],
    words: [
      ["number", "number"],
      ["üks", "one"],
      ["kaks", "two"],
      ["kolm", "three"],
      ["neli", "four"],
      ["viis", "five"],
      ["kuus", "six"],
      ["seitse", "seven"],
      ["kaheksa", "eight"],
      ["üheksa", "nine"],
      ["kümme", "ten"],
      ["sada", "hundred"],
      ["tuhat", "thousand"],
      ["esimene", "first", "ADJECTIVE"],
      ["teine", "second, other", "ADJECTIVE"],
      ["pool", "half"],
    ],
  }),

  unit({
    id: "kodu",
    title: "Kodu",
    subtitle: "Home and everyday objects",
    icon: "House",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Describe your home and say where things are in it.",
    blurb: "Things you can point at, the easiest place to meet the inessive (toas, köögis).",
    grammar: ["inessive", "nominative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["inimesed"],
    words: [
      ["kodu", "home"],
      ["maja", "house"],
      ["tuba", "room"],
      ["köök", "kitchen"],
      ["korter", "flat, apartment"],
      ["uks", "door"],
      ["aken", "window"],
      ["laud", "table"],
      ["tool", "chair"],
      ["voodi", "bed"],
      ["raamat", "book"],
      ["arvuti", "computer"],
      ["telefon", "telephone"],
      ["võti", "key"],
      ["klaas", "glass"],
      ["tass", "cup"],
      ["pilt", "picture"],
      ["sein", "wall"],
      ["põrand", "floor"],
    ],
  }),

  unit({
    id: "sook-ja-jook",
    title: "Söök ja jook",
    subtitle: "Food and drink",
    icon: "Utensils",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Order food, shop for groceries and say what you like to eat.",
    blurb: "Enough to order, shop and read a menu. The partitive lives here (ma joon kohvi).",
    grammar: ["partitive", "object"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kodu"],
    words: [
      ["toit", "food"],
      ["söök", "food, a meal"],
      ["jook", "drink"],
      ["leib", "bread (dark)"],
      ["sai", "bread (white)"],
      ["kohv", "coffee"],
      ["vesi", "water"],
      ["piim", "milk"],
      ["mahl", "juice"],
      ["liha", "meat"],
      ["kala", "fish"],
      ["õun", "apple"],
      ["kartul", "potato"],
      ["juust", "cheese"],
      ["muna", "egg"],
      ["või", "butter"],
      ["sool", "salt"],
      ["suhkur", "sugar"],
      ["supp", "soup"],
    ],
  }),

  unit({
    id: "aeg",
    title: "Aeg",
    subtitle: "Days, hours and when things happen",
    icon: "Clock",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Tell the time, name the days, and say when something happens.",
    blurb: "Time words carry the adessive and elative constantly, hommikul, esmaspäevast.",
    grammar: ["adessive", "elative", "time-expressions"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["arvud"],
    words: [
      ["aeg", "time"],
      ["päev", "day"],
      ["öö", "night"],
      ["hommik", "morning"],
      ["õhtu", "evening"],
      ["nädal", "week"],
      ["kuu", "month, moon"],
      ["aasta", "year"],
      ["tund", "hour, lesson"],
      ["minut", "minute"],
      ["kell", "clock, o'clock"],
      ["esmaspäev", "Monday"],
      ["teisipäev", "Tuesday"],
      ["kolmapäev", "Wednesday"],
      ["neljapäev", "Thursday"],
      ["reede", "Friday"],
      ["laupäev", "Saturday"],
      ["pühapäev", "Sunday"],
    ],
  }),

  unit({
    id: "pohiverbid",
    title: "Põhiverbid",
    subtitle: "The irregular core",
    icon: "Zap",
    level: "A1",
    module: "Tegevused",
    canDo: "Build a simple sentence in the present tense about what you do.",
    blurb: "Verbs that break the rules and are used constantly. Learn these as forms, not patterns.",
    grammar: ["present-tense", "olema", "negation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["kodu"],
    words: [
      ["olema", "to be"],
      ["minema", "to go"],
      ["tulema", "to come"],
      ["tegema", "to do, to make"],
      ["saama", "to get, to become"],
      ["pidama", "to have to, to keep"],
      ["sööma", "to eat"],
      ["jooma", "to drink"],
      ["tooma", "to bring"],
      ["viima", "to take away"],
      ["andma", "to give"],
      ["võtma", "to take"],
      ["panema", "to put"],
      ["jääma", "to stay, to remain"],
    ],
  }),

  unit({
    id: "iga-paev",
    title: "Iga päev",
    subtitle: "Everyday actions",
    icon: "Footprints",
    level: "A1",
    module: "Tegevused",
    canDo: "Describe your daily routine from waking up to going to bed.",
    blurb: "What you do all day, in the two infinitives Estonian actually uses.",
    grammar: ["present-tense", "infinitives"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["pohiverbid"],
    words: [
      ["tahtma", "to want"],
      ["teadma", "to know (a fact)"],
      ["tundma", "to know (a person), to feel"],
      ["nägema", "to see"],
      ["kuulma", "to hear"],
      ["rääkima", "to speak"],
      ["ütlema", "to say"],
      ["küsima", "to ask"],
      ["vastama", "to answer"],
      ["lugema", "to read, to count"],
      ["kirjutama", "to write"],
      ["õppima", "to learn, to study"],
      ["töötama", "to work"],
      ["elama", "to live"],
      ["magama", "to sleep"],
      ["ärkama", "to wake up"],
      ["istuma", "to sit"],
      ["seisma", "to stand"],
    ],
  }),

  unit({
    id: "omadussonad",
    title: "Omadussõnad",
    subtitle: "Describing things",
    icon: "Palette",
    level: "A1",
    module: "Kirjeldamine",
    canDo: "Describe a thing or a person with an adjective that agrees with it.",
    blurb: "Adjectives agree with their noun in Estonian, so every one you learn pays for itself.",
    grammar: ["adjective-agreement", "nominative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kodu"],
    words: [
      ["suur", "big, large", "ADJECTIVE"],
      ["väike", "small", "ADJECTIVE"],
      ["hea", "good", "ADJECTIVE"],
      ["halb", "bad", "ADJECTIVE"],
      ["uus", "new", "ADJECTIVE"],
      ["vana", "old", "ADJECTIVE"],
      ["noor", "young", "ADJECTIVE"],
      ["pikk", "long, tall", "ADJECTIVE"],
      ["lühike", "short", "ADJECTIVE"],
      ["kiire", "fast, quick", "ADJECTIVE"],
      ["aeglane", "slow", "ADJECTIVE"],
      ["kallis", "expensive, dear", "ADJECTIVE"],
      ["odav", "cheap", "ADJECTIVE"],
      ["ilus", "beautiful", "ADJECTIVE"],
      ["tore", "nice, lovely", "ADJECTIVE"],
      ["raske", "difficult, heavy", "ADJECTIVE"],
      ["kerge", "easy, light", "ADJECTIVE"],
      ["lihtne", "simple", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "varvid",
    title: "Värvid",
    subtitle: "Colours",
    icon: "Paintbrush",
    level: "A1",
    module: "Kirjeldamine",
    canDo: "Name colours and describe what something looks like.",
    blurb: "Short, concrete, and every one of them declines like an ordinary adjective.",
    grammar: ["adjective-agreement"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["omadussonad"],
    words: [
      ["värv", "colour"],
      ["punane", "red", "ADJECTIVE"],
      ["sinine", "blue", "ADJECTIVE"],
      ["roheline", "green", "ADJECTIVE"],
      ["kollane", "yellow", "ADJECTIVE"],
      ["must", "black", "ADJECTIVE"],
      ["valge", "white", "ADJECTIVE"],
      ["hall", "grey", "ADJECTIVE"],
      ["pruun", "brown", "ADJECTIVE"],
      ["roosa", "pink", "ADJECTIVE"],
      ["lilla", "purple", "ADJECTIVE"],
      ["hele", "light, pale", "ADJECTIVE"],
      ["tume", "dark", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "riided",
    title: "Riided",
    subtitle: "Clothes and what you wear",
    icon: "Shirt",
    level: "A1",
    module: "Kirjeldamine",
    canDo: "Say what you are wearing and shop for clothes by size and colour.",
    blurb: "A shop conversation you will have in your first week, and a pile of easy nouns.",
    grammar: ["adjective-agreement", "partitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["varvid"],
    words: [
      ["särk", "shirt"],
      ["kleit", "dress"],
      ["seelik", "skirt"],
      ["king", "shoe"],
      ["sokk", "sock"],
      ["müts", "hat"],
      ["mantel", "coat"],
      ["jope", "jacket"],
      ["sall", "scarf"],
      ["kinnas", "glove"],
      ["taskurätik", "handkerchief"],
      ["vöö", "belt"],
      ["riie", "cloth, fabric"],
    ],
  }),

  unit({
    id: "ilm",
    title: "Ilm",
    subtitle: "Weather",
    icon: "CloudSun",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Talk about the weather, which in Estonia is never small talk for long.",
    blurb: "Half of every Estonian conversation opens here, and the vocabulary is tiny.",
    grammar: ["olema", "adjective-agreement"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["omadussonad"],
    words: [
      ["ilm", "weather"],
      ["päike", "sun"],
      ["vihm", "rain"],
      ["lumi", "snow"],
      ["tuul", "wind"],
      ["pilv", "cloud"],
      ["torm", "storm"],
      ["jää", "ice"],
      ["udu", "fog"],
      ["kraad", "degree"],
      ["külm", "cold", "ADJECTIVE"],
      ["soe", "warm", "ADJECTIVE"],
      ["kuum", "hot", "ADJECTIVE"],
      ["märg", "wet", "ADJECTIVE"],
      ["kuiv", "dry", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "ostmine",
    title: "Poes ja tänaval",
    subtitle: "Shopping and getting around",
    icon: "ShoppingBag",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Buy something, ask the price, and find your way to a place in town.",
    blurb: "Buying, paying, going. Verbs and places together, because that is how they turn up.",
    grammar: ["partitive", "illative", "allative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["sook-ja-jook", "arvud"],
    words: [
      ["pood", "shop"],
      ["turg", "market"],
      ["raha", "money"],
      ["hind", "price"],
      ["pilet", "ticket"],
      ["ostma", "to buy"],
      ["müüma", "to sell"],
      ["maksma", "to pay, to cost"],
      ["linn", "town, city"],
      ["tänav", "street"],
      ["tee", "road, tea"],
      ["buss", "bus"],
      ["rong", "train"],
      ["auto", "car"],
      ["jaam", "station"],
      ["park", "park"],
    ],
  }),

  unit({
    id: "kus-ja-kuhu",
    title: "Kus ja kuhu",
    subtitle: "Places and directions",
    icon: "Map",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Ask where something is and understand the directions you are given.",
    blurb: "Estonian answers 'where' and 'where to' with different cases. This is that split.",
    grammar: ["inessive", "illative", "elative", "allative", "adessive", "ablative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["ostmine", "kodu"],
    words: [
      ["koht", "place"],
      ["kesklinn", "town centre"],
      ["väljak", "square"],
      ["sild", "bridge"],
      ["nurk", "corner"],
      ["kool", "school"],
      ["töö", "work"],
      ["haigla", "hospital"],
      ["kirik", "church"],
      ["rand", "beach"],
      ["ülikool", "university"],
      ["kohvik", "café"],
      ["restoran", "restaurant"],
      ["hotell", "hotel"],
    ],
  }),

  /*
    THE WORDS EVERY SENTENCE IS MADE OF, WHICH THE COURSE HAD LEFT OUT.

    Fourteen units of nouns, verbs and adjectives, and no unit for the words
    between them: nobody asking "kes?" or "millal?" or looking up "täna" or
    "peal" found anything, and two of the twelve months were missing from the
    dictionary altogether. These six are appended after the fourteen so that
    the first three units at A1, which is what first run builds a deck from,
    stay what they were. Every lemma is still a request the harvest either
    honours or reports, and a pronoun is harvested as a nominal because it
    declines like one: `kes`, `kelle`, `keda`, and the case table follows.
  */
  unit({
    id: "kusisonad",
    title: "Küsisõnad",
    subtitle: "Question words",
    icon: "CircleHelp",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Ask who, what, where, when, why and how, and follow the question when it comes back.",
    blurb: "Every conversation is a question first. These are the words it starts with.",
    grammar: ["word-order"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["tervitused"],
    words: [
      ["kes", "who", "PRONOUN"],
      ["mis", "what", "PRONOUN"],
      ["kus", "where", "ADVERB"],
      ["kuhu", "where to", "ADVERB"],
      ["kust", "where from", "ADVERB"],
      ["millal", "when", "ADVERB"],
      ["miks", "why", "ADVERB"],
      ["kuidas", "how", "ADVERB"],
      ["kas", "whether (opens a yes or no question)", "ADVERB"],
      ["milline", "which, what kind of", "PRONOUN"],
      ["kumb", "which of the two", "PRONOUN"],
      ["mitu", "how many", "PRONOUN"],
      ["palju", "much, many, a lot", "ADVERB"],
      ["kui", "how, as, if, than", "ADVERB"],
    ],
  }),

  unit({
    id: "asesonad",
    title: "Asesõnad",
    subtitle: "Pronouns",
    icon: "Users",
    level: "A1",
    module: "Esimesed sammud",
    canDo: "Say I, you, he, we and they, point at this and that, and put each in the case the sentence needs.",
    blurb: "Six persons and a pointer. They decline like nouns, and the short forms are what you hear.",
    grammar: ["nominative", "genitive", "partitive"],
    // No case cards from the seed alone: a pronoun's everyday case forms are
    // the short ones (`mulle`, `mul`), which no rule over the genitive reaches,
    // and a card answering `minule` would mark the form everybody says wrong.
    // Ekilex records both, so an enriched entry shows the pair on its table.
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["inimesed"],
    words: [
      ["mina", "I", "PRONOUN"],
      ["sina", "you (one person)", "PRONOUN"],
      ["tema", "he, she", "PRONOUN"],
      ["meie", "we", "PRONOUN"],
      ["teie", "you (several people, or one politely)", "PRONOUN"],
      ["nemad", "they", "PRONOUN"],
      ["see", "this, it", "PRONOUN"],
      ["too", "that (one over there)", "PRONOUN"],
      ["ise", "self, myself, yourself", "PRONOUN"],
      ["keegi", "somebody, anybody", "PRONOUN"],
      ["miski", "something, anything", "PRONOUN"],
      ["kõik", "all, everything, everybody", "PRONOUN"],
      ["igaüks", "everyone, each one", "PRONOUN"],
      ["mõni", "some, a few", "PRONOUN"],
      ["iga", "every, each", "PRONOUN"],
    ],
  }),

  unit({
    id: "millal",
    title: "Millal ja kui tihti",
    subtitle: "When, and how often",
    icon: "Clock",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Say when something happens and how often, from today to hardly ever.",
    blurb: "No case endings at all: twenty adverbs that carry half of every plan.",
    grammar: ["time-expressions"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["aeg"],
    words: [
      ["täna", "today", "ADVERB"],
      ["homme", "tomorrow", "ADVERB"],
      ["eile", "yesterday", "ADVERB"],
      ["ülehomme", "the day after tomorrow", "ADVERB"],
      ["üleeile", "the day before yesterday", "ADVERB"],
      ["nüüd", "now", "ADVERB"],
      ["praegu", "right now, at the moment", "ADVERB"],
      ["kohe", "at once, straight away", "ADVERB"],
      ["varsti", "soon", "ADVERB"],
      ["hiljem", "later", "ADVERB"],
      ["alati", "always", "ADVERB"],
      ["tihti", "often", "ADVERB"],
      ["sageli", "often, frequently", "ADVERB"],
      ["harva", "rarely, seldom", "ADVERB"],
      ["mõnikord", "sometimes", "ADVERB"],
      ["kunagi", "ever, at some time; never (with a negative)", "ADVERB"],
      ["juba", "already", "ADVERB"],
      ["veel", "still, yet, more", "ADVERB"],
      ["jälle", "again", "ADVERB"],
      ["ammu", "long ago, for a long time", "ADVERB"],
    ],
  }),

  unit({
    id: "kohasonad",
    title: "Peal, all, ees, taga",
    subtitle: "Where things are",
    icon: "Compass",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Say what is on, under, in front of, behind and next to what.",
    blurb: "Most of these come after the noun and put it in the genitive: laua peal, not peal laud. A few go in front and ask for another case, and this unit has both.",
    grammar: ["genitive", "adessive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["kus-ja-kuhu"],
    words: [
      ["peal", "on, on top of", "ADVERB"],
      ["all", "under, below", "ADVERB"],
      ["ees", "in front of", "ADVERB"],
      ["taga", "behind", "ADVERB"],
      ["kõrval", "next to, beside", "ADVERB"],
      ["juures", "at, by, with (a person or a place)", "ADVERB"],
      ["vahel", "between", "ADVERB"],
      ["sees", "inside", "ADVERB"],
      ["keskel", "in the middle of", "ADVERB"],
      ["vastas", "opposite", "ADVERB"],
      ["ümber", "around", "ADVERB"],
      ["üle", "over, across", "ADVERB"],
      ["läbi", "through", "ADVERB"],
      ["koos", "together with", "ADVERB"],
      ["ilma", "without", "ADVERB"],
      ["enne", "before", "ADVERB"],
      ["pärast", "after", "ADVERB"],
      ["lähedal", "near, close to", "ADVERB"],
      ["kohal", "above, over", "ADVERB"],
      ["mööda", "along", "ADVERB"],
    ],
  }),

  unit({
    id: "kuud",
    title: "Kuud ja tähtpäevad",
    subtitle: "Months and the days that matter",
    icon: "CalendarRange",
    level: "A1",
    module: "Igapäevaelu",
    canDo: "Name the months, give a date, and say when your birthday is.",
    blurb: "Twelve months, all in the inessive when something happens in them: jaanuaris, mais.",
    grammar: ["inessive", "time-expressions"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["aeg"],
    words: [
      ["jaanuar", "January"],
      ["veebruar", "February"],
      ["märts", "March"],
      ["aprill", "April"],
      ["mai", "May"],
      ["juuni", "June"],
      ["juuli", "July"],
      ["august", "August"],
      ["september", "September"],
      ["oktoober", "October"],
      ["november", "November"],
      ["detsember", "December"],
      ["kuupäev", "date"],
      ["sünnipäev", "birthday"],
      ["tähtpäev", "anniversary, special day"],
      ["jaanipäev", "Midsummer Day"],
      ["nädalavahetus", "weekend"],
      ["puhkepäev", "day off"],
    ],
  }),

  unit({
    id: "riigid",
    title: "Riigid ja rahvad",
    subtitle: "Countries and peoples",
    icon: "Landmark",
    level: "A1",
    module: "Maailm ümber",
    canDo: "Say where you are from, what you are, and which language you speak.",
    blurb: "The neighbours first. A nationality ends in -lane. Eesti and Soome take the inside cases, Eestist; the countries ending in -maa take the outside ones, the way the islands do: Saksamaal, Saksamaale, Saksamaalt.",
    grammar: ["elative", "nominative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kus-ja-kuhu"],
    words: [
      ["Eesti", "Estonia"],
      ["Soome", "Finland"],
      ["Läti", "Latvia"],
      ["Venemaa", "Russia"],
      ["Rootsi", "Sweden"],
      ["Saksamaa", "Germany"],
      ["Inglismaa", "England"],
      ["Ameerika", "America"],
      ["Euroopa", "Europe"],
      ["eestlane", "an Estonian"],
      ["soomlane", "a Finn"],
      ["lätlane", "a Latvian"],
      ["venelane", "a Russian"],
      ["rootslane", "a Swede"],
      ["sakslane", "a German"],
      ["inglane", "an English person"],
      ["ameeriklane", "an American"],
      ["välismaalane", "foreigner"],
      ["kodumaa", "homeland"],
      ["rahvus", "nationality"],
    ],
  }),
] as const;
