/**
 * C2 — from control to command.
 *
 * There is an honest question about whether an app can take anybody to C2, and
 * the answer is no: C2 is earned by reading, arguing and living in a language,
 * not by finishing units. What an app can do is name the ground, which is what
 * this level does. Each unit is a specialised register or a fine distinction —
 * the things a C1 speaker still gets subtly wrong — with the vocabulary and the
 * attested sentences to work on them, and every one says plainly that the
 * practice happens outside the app.
 */
import { unit } from "./types";

export const C2 = [
  unit({
    id: "stilistika",
    title: "Stilistika",
    subtitle: "Style as a choice",
    icon: "Feather",
    level: "C2",
    module: "Meisterlikkus",
    canDo: "Rewrite the same paragraph in four styles and say what each one costs.",
    blurb: "At C2 every sentence is a decision. This unit is about noticing the decisions.",
    grammar: ["register", "word-order", "emphasis"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["nuansid"],
    words: [
      ["stiil", "style"],
      ["väljenduslaad", "manner of expression"],
      ["sõnavalik", "word choice"],
      ["lauseehitus", "sentence construction"],
      ["kordus", "repetition"],
      ["rütm", "rhythm"],
      ["ülevus", "loftiness"],
      ["lakooniline", "laconic", "ADJECTIVE"],
      ["ohtrasõnaline", "verbose", "ADJECTIVE"],
      ["elegantne", "elegant", "ADJECTIVE"],
      ["kantseliitlik", "bureaucratic", "ADJECTIVE"],
      ["voolav", "flowing", "ADJECTIVE"],
      ["stiilitaju", "sense of style"],
      ["keelekasutaja", "language user"],
      ["väljendusrikkus", "expressiveness"],
      ["tihedus", "density"],
      ["sagedus", "frequency"],
      ["nüansirikas", "nuanced", "ADJECTIVE"],
      ["selgesõnaline", "explicit", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "iroonia",
    title: "Iroonia ja huumor",
    subtitle: "Saying the opposite on purpose",
    icon: "Laugh",
    level: "C2",
    module: "Meisterlikkus",
    canDo: "Detect irony in Estonian and produce it without being misread.",
    blurb: "The last thing you learn to hear, and the easiest thing to get wrong in a second language.",
    grammar: ["irony", "register", "emphasis"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["stilistika"],
    words: [
      ["iroonia", "irony"],
      ["sarkasm", "sarcasm"],
      ["huumor", "humour"],
      ["paroodia", "parody"],
      ["vihje", "hint"],
      ["teravmeelsus", "wit"],
      ["pilge", "mockery"],
      ["kahemõtteline", "ambiguous", "ADJECTIVE"],
      ["terav", "sharp", "ADJECTIVE"],
      ["kuiv", "dry (of humour)", "ADJECTIVE"],
      ["irvitama", "to sneer"],
      ["naljatama", "to joke"],
      ["etteheide", "reproach"],
      ["häbistav", "shaming", "ADJECTIVE"],
      ["mõnitus", "taunt"],
      ["koomiline", "comic", "ADJECTIVE"],
      ["tabavus", "aptness"],
      ["arusaamatus", "misunderstanding"],
    ],
  }),

  unit({
    id: "juriidiline",
    title: "Juriidiline keel",
    subtitle: "The language of contracts",
    icon: "FileText",
    level: "C2",
    module: "Erialakeeled",
    canDo: "Read a contract or a statute and say precisely what it obliges.",
    blurb: "A register built to remove ambiguity, at the cost of every other virtue.",
    grammar: ["impersonal", "nominalisation", "subordination"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["oigus", "nuansid"],
    words: [
      ["säte", "provision"],
      ["paragrahv", "section, paragraph"],
      ["kehtivus", "validity, force"],
      ["jõustumine", "entry into force"],
      ["vastutus", "liability"],
      ["tingimus", "condition, term"],
      ["kohustuslik", "obligatory", "ADJECTIVE"],
      ["siduv", "binding", "ADJECTIVE"],
      ["tühine", "void, negligible", "ADJECTIVE"],
      ["sätestama", "to stipulate"],
      ["kohustama", "to oblige"],
      ["jõustuma", "to come into force"],
      ["õigusakt", "legal act"],
      ["määrus", "regulation"],
      ["hagiavaldus", "statement of claim"],
      ["kostja", "defendant"],
      ["hageja", "plaintiff"],
      ["menetlus", "proceedings"],
      ["õiguskord", "legal order"],
    ],
  }),

  unit({
    id: "meditsiiniline",
    title: "Erialakeel",
    subtitle: "Technical and medical registers",
    icon: "Activity",
    level: "C2",
    module: "Erialakeeled",
    canDo: "Follow a specialist text in a field that is not yours, and translate it into plain Estonian.",
    blurb: "The skill is not the terminology. It is explaining it to somebody who lacks it.",
    grammar: ["nominalisation", "impersonal", "register"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["tervishoid", "teadustoo"],
    words: [
      ["termin", "term"],
      ["oskussõna", "technical term"],
      ["määratlus", "definition"],
      ["klassifikatsioon", "classification"],
      ["tunnus", "feature, characteristic"],
      ["näidustus", "indication"],
      ["kõrvaltoime", "side effect"],
      ["taluvus", "tolerance"],
      ["spetsiifiline", "specific", "ADJECTIVE"],
      ["üldarusaadav", "generally comprehensible", "ADJECTIVE"],
      ["lihtsustama", "to simplify"],
      ["defineerima", "to define"],
      ["sümptom", "symptom"],
      ["patsient", "patient"],
      ["annus", "dose"],
      ["vastunäidustus", "contraindication"],
      ["erialane", "specialist", "ADJECTIVE"],
      ["üldkeel", "general language"],
    ],
  }),

  unit({
    id: "publitsistika",
    title: "Publitsistika",
    subtitle: "The essay and the column",
    icon: "PenLine",
    level: "C2",
    module: "Erialakeeled",
    canDo: "Write an opinion column that sounds written rather than translated.",
    blurb: "The most demanding public register, because it has to be precise and readable at once.",
    grammar: ["word-order", "emphasis", "cohesion"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["retoorika", "stilistika"],
    words: [
      ["arvamuslugu", "opinion piece"],
      ["juhtkiri", "editorial"],
      ["essee", "essay"],
      ["käsitlus", "treatment, approach"],
      ["teravus", "sharpness, poignancy"],
      ["provokatsioon", "provocation"],
      ["üldsus", "the public"],
      ["poleemika", "polemic"],
      ["kaalukas", "weighty", "ADJECTIVE"],
      ["läbinägelik", "perceptive", "ADJECTIVE"],
      ["sõnastama", "to formulate"],
      ["esitama", "to present, to put forward"],
      ["kolumnist", "columnist"],
      ["kommentaar", "commentary"],
      ["avalikkus", "the public sphere"],
      ["teravmeelne", "witty", "ADJECTIVE"],
      ["provokatiivne", "provocative", "ADJECTIVE"],
      ["lugejaskond", "readership"],
    ],
  }),

  unit({
    id: "tolkimine",
    title: "Tõlkimine",
    subtitle: "What does not carry across",
    icon: "Languages",
    level: "C2",
    module: "Meisterlikkus",
    canDo: "Translate idiomatically rather than literally, and defend the choice.",
    blurb: "Translation is where you discover which of your Estonian was actually English.",
    grammar: ["collocation", "register", "word-order"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["idioomid", "nuansid"],
    words: [
      ["tõlge", "translation"],
      ["tõlkija", "translator"],
      ["vaste", "equivalent"],
      ["lähtekeel", "source language"],
      ["sihtkeel", "target language"],
      ["sõnasõnaline", "literal", "ADJECTIVE"],
      ["vabatõlge", "free translation"],
      ["mugandus", "adaptation"],
      ["tõlkeviga", "translation error"],
      ["edasi andma", "to convey", "VERB"],
      ["kohandama", "to adapt"],
      ["tabama", "to capture, to hit"],
      ["originaal", "original"],
      ["olenev", "depending", "ADJECTIVE"],
      ["terminoloogia", "terminology"],
      ["toimetamine", "editing"],
      ["ekvivalent", "equivalent"],
      ["keelevahetus", "language switching"],
    ],
  }),

  unit({
    id: "keelevariandid",
    title: "Keelevariandid",
    subtitle: "Dialects and variation",
    icon: "MapPinned",
    level: "C2",
    module: "Meisterlikkus",
    canDo: "Recognise where a speaker is from and what their choices signal.",
    blurb: "Estonian is small and far from uniform. Hearing the difference is a C2 skill.",
    grammar: ["variation", "register"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["stilistika"],
    words: [
      ["murre", "dialect"],
      ["murrak", "local dialect"],
      ["hääldus", "pronunciation"],
      ["rõhk", "stress, accent"],
      ["kõnepruuk", "way of speaking, parlance"],
      ["keelekasutus", "language use"],
      ["norm", "norm"],
      ["kõrvalekalle", "deviation"],
      ["arhailine", "archaic", "ADJECTIVE"],
      ["piirkondlik", "regional", "ADJECTIVE"],
      ["levinud", "widespread", "ADJECTIVE"],
      ["eristuma", "to stand out, to differ"],
      ["kirjaviis", "orthography, spelling"],
      ["aktsent", "accent"],
      ["põlvkondlik", "generational", "ADJECTIVE"],
      ["keelenorm", "language norm"],
      ["kõnekeelne", "colloquial", "ADJECTIVE"],
      ["murdesõna", "dialect word"],
      ["standardkeel", "standard language"],
    ],
  }),

  unit({
    id: "tapsus",
    title: "Täpsus",
    subtitle: "Getting the exact word",
    icon: "Crosshair",
    level: "C2",
    module: "Meisterlikkus",
    canDo: "Distinguish sets of near-synonyms that no dictionary separates for you.",
    blurb: "The difference between correct Estonian and the right Estonian.",
    grammar: ["collocation", "nuance"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["tolkimine"],
    words: [
      ["täpsustama", "to make precise"],
      ["eristus", "distinction"],
      ["piiritlema", "to delimit"],
      ["määratlemine", "definition, delimitation"],
      ["kitsendus", "restriction"],
      ["laiendus", "extension"],
      ["kattuvus", "overlap"],
      ["üheselt", "unambiguously", "ADVERB"],
      ["täpselt", "exactly", "ADVERB"],
      ["ligilähedaselt", "approximately", "ADVERB"],
      ["üldine", "general", "ADJECTIVE"],
      ["kitsas", "narrow", "ADJECTIVE"],
      ["ligikaudne", "approximate", "ADJECTIVE"],
      ["konkreetne", "concrete", "ADJECTIVE"],
      ["mitmetähenduslik", "polysemous", "ADJECTIVE"],
      ["selgesti", "clearly", "ADVERB"],
      ["piiritletud", "delimited", "ADJECTIVE"],
      ["ähmasus", "vagueness"],
      ["sõnastus", "wording"],
    ],
  }),

  unit({
    id: "keelemang",
    title: "Keelemäng",
    subtitle: "Playing with the language",
    icon: "Puzzle",
    level: "C2",
    module: "Meisterlikkus",
    canDo: "Make a pun, read a poem's form, and enjoy Estonian rather than operate it.",
    blurb: "The point of all of it. If you can be funny in a language, you have it.",
    grammar: ["idiom", "variation", "emphasis"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["iroonia", "tapsus"],
    words: [
      ["sõnamäng", "wordplay, pun"],
      ["riim", "rhyme"],
      ["mõistatus", "riddle"],
      ["kõla", "sound, resonance"],
      ["kujund", "figure, image"],
      ["mitmetähenduslikkus", "polysemy"],
      ["leidlik", "inventive", "ADJECTIVE"],
      ["vaimukas", "witty", "ADJECTIVE"],
      ["ootamatu", "unexpected", "ADJECTIVE"],
      ["vallatu", "playful, mischievous", "ADJECTIVE"],
      ["mängima", "to play"],
      ["moonutama", "to distort"],
      ["kalambuur", "pun"],
      ["alliteratsioon", "alliteration"],
      ["luuletus", "poem"],
      ["rütmika", "rhythmics"],
      ["naljakas", "funny", "ADJECTIVE"],
      ["nutikas", "clever", "ADJECTIVE"],
      ["keeleoskus", "language skill"],
    ],
  }),

  unit({
    id: "meisterlikkus",
    title: "Vaba valdamine",
    subtitle: "Where the app stops",
    icon: "Trophy",
    level: "C2",
    module: "Meisterlikkus",
    canDo: "Work in Estonian without thinking about Estonian.",
    blurb:
      "The last unit is honest: C2 is finished by reading, arguing and living in the language, " +
      "not by finishing units. This one hands you the reading list and gets out of the way.",
    grammar: ["register", "variation", "collocation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["keelemang", "publitsistika", "juriidiline"],
    words: [
      ["valdamine", "command, mastery"],
      ["emakeel", "native language"],
      ["vilumus", "proficiency, skill"],
      ["harjumuspärane", "habitual", "ADJECTIVE"],
      ["loomulik", "natural", "ADJECTIVE"],
      ["pingutus", "effort"],
      ["süvenema", "to become absorbed"],
      ["harjuma", "to get used to"],
      ["kohanema", "to adapt"],
      ["omaks võtma", "to adopt, to embrace", "VERB"],
      ["enesekindlus", "self-assurance"],
      ["kogenud", "experienced", "ADJECTIVE"],
      ["sujuv", "smooth", "ADJECTIVE"],
      ["arusaamine", "understanding"],
      ["keelekeskkond", "language environment"],
      ["igapäevane", "everyday", "ADJECTIVE"],
      ["vabalt", "freely", "ADVERB"],
    ],
  }),
] as const;
